config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
    	passwords: 'users/passwords'
      }

    resources :contacts, :except => [:edit, :update, :destroy]
    resources :aboutme, :only => [:index]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col l8 m6 s12">
          <h5 class="white-text">¿Quién soy?</h5>
          <p class="grey-text text-lighten-4" style="text-align: justify;">¡Hola! ¿Que tal? Mi nombre es Nayzareth, pero tu puedes llamarme Nayza, me encanta la programación web y pretendo día a día aprender mas sobre ella.</p>
        </div>

        <div class="col l4 m6 s12">
          <h5 class="white-text">Redes Sociales</h5>
          <ul>
            <!--<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.es/"           title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"          title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>-->
            <li><a class="white-text" href="https://www.linkedin.com/in/nayzareth-hurtado-acosta/"><%= image_tag("in.png", class: 'img')%> Nayzareth Hurtado Acosta</a></li>
            <!--<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.es/"           title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"          title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>-->
            <li><%= image_tag("w.png", class: 'img')%> +58 414 8076973</li>
            <!--<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.es/"           title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"          title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>-->
            <li><%= image_tag("g.png", class: 'img')%> hurtado.nayza@gmail.com</li>
            <!--<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.es/"           title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"          title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>-->
            <li><a class="white-text"><%= image_tag("ig.png", class: 'img')%> @hurtado.nayza</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="footer-copyright">
      <div class="container">
        Nayzareth Hurtado - Ingeniera en informática.
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <%= link_to 'NH', root_path, id: 'logo-container', class: 'brand-logo'%>
      <ul class="right hide-on-med-and-down">
        <li><a id="lista" href="#">Portafolio</a></li>
        <li><%= link_to 'Contáctame', new_contact_path, id: 'lista'%></li>
        <li><%= link_to 'Sobre mí', aboutme_index_path, id: 'lista'%></li>
        <% if signed_in? %>
          <li><%= link_to 'Comentarios', contacts_path, id: 'lista'%></li>
          <li><%= link_to 'Salir', destroy_user_session_path, method: :delete, id: 'lista'%></li>
        <% end %>
      </ul>

      <ul id="nav-mobile" class="sidenav">

        <li><div class="user-view">
          <div class="background">
            <%= image_tag("back.png")%>
          </div>
          <a href="#user"><%= image_tag("logosx.png", class: 'circle')%></a>
          <a href="#name"><span class="name" id="lista">Nayzareth Hurtado</span></a>
          <a href="#phone"><span class="phone" id="lista">+58 414 8076973</span></a>
          <a href="#email"><span class="email" id="lista">hurtado.nayza@gmail.com</span></a>
        </div></li>

        <li><a id="lista" href="#">Portafolio</a></li>
        <li><%= link_to 'Contáctame', new_contact_path, id: 'lista'%></li>
        <li><%= link_to 'Sobre mí', aboutme_index_path, id: 'lista'%></li>
        <% if signed_in? %>
          <li><%= link_to 'Comentarios', contacts_path, id: 'lista'%></li>
          <li><%= link_to 'Salir', destroy_user_session_path, method: :delete, id: 'lista'%></li>
        <% end %>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>
<script>
(function($){
  $(function(){

    $('.sidenav').sidenav();
    $('.parallax').parallax();

  }); // end of document ready
})(jQuery); // end of jQuery name space
</script>

app/views/layouts/_parallaxdown.html.erb
<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Todos tenemos tiempo para lo que tenemos ganas</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><%= image_tag("b6.jpg")%></div>
</div>

app/views/layouts/_parallaxup.html.erb
<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="text-white">“Aprende del ayer, vive para hoy, ten esperanza para el mañana. Lo importante es no dejar de hacerse preguntas.” <br>-Albert Einstein</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><%= image_tag("c5.jpg")%></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favi.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= render "layouts/parallaxup"%>

    <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12">
          <p class="notice"><%= notice %></p>
          <%= yield %> 
        </div>
      </div>

    </div>
  </div>
    <%= render "layouts/footer"%>
  </body>
</html>